### PR TITLE
Update to Kotlin 1.3.11

### PR DESCRIPTION
**Pull request by ZacSweers**

### CODE REVIEW

**Comment by ZacSweers** [comment]
I have no idea how to update submodules in git/github apparently

**Comment by ZacSweers** [comment]
I now have an idea how to update submodules in git/github apparently

**Comment by wyaeld** [comment]
@Takhion Could you take a look at this please.  Getting a lot of classpath warnings on projects due to this module being the only thing compiled at 1.2.  Square's moshi-codegen module is pulling it in

**Comment by audkar** [comment]
KT could already be bumped to 1.3.21 ;)

**Pull request closed without merging**
